# Created using wingetcreate 1.2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: ShiningLight.OpenSSL
PackageVersion: 3.1.2
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- openssl
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: wix
  InstallerUrl: https://slproweb.com/download/Win64OpenSSL-3_1_2.msi
  InstallerSha256: 0FE854C1A73537E304C13503ABA9EFB7C4EDF867F16F3A22AD686FAB493F7FC7
  ProductCode: '{DB2719CA-1430-497A-B9F0-58EFA7CC00A3}'
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: wix
  InstallerUrl: https://slproweb.com/download/Win32OpenSSL-3_1_2.msi
  InstallerSha256: B052B295239BC14865FBAC04D9904E8744796FBE693B8EAE3D6520CDA03150A4
  ProductCode: '{23C59E37-6ACC-4DAA-966D-3C0C6AF19BCE}'
- Architecture: x64
  InstallerType: inno
  InstallerUrl: https://slproweb.com/download/Win64OpenSSL-3_1_2.exe
  InstallerSha256: 2889BCB807FA91CE4A93BBF10143EFCBB9B62B1BF5A827F1BE50395559F3E0F2
  ProductCode: OpenSSL (64-bit)_is1
  AppsAndFeaturesEntries:
  - DisplayName: OpenSSL 3.1.2 (64-bit)
    Publisher: OpenSSL Win64 Installer Team
    ProductCode: OpenSSL (64-bit)_is1
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://slproweb.com/download/Win32OpenSSL-3_1_2.exe
  InstallerSha256: D28DE0092B8F78FC52DA8FF15C84A1A3486A6D60055D70BBCACA368052D29264
  ProductCode: OpenSSL (32-bit)_is1
  AppsAndFeaturesEntries:
  - DisplayName: OpenSSL 3.1.2 (32-bit)
    Publisher: OpenSSL Win32 Installer Team
    ProductCode: OpenSSL (32-bit)_is1
ManifestType: installer
ManifestVersion: 1.4.0
